---
kind: pipeline
type: docker
name: build

volumes:
  - name: bundle
    host:
      path: /home/data/drone/gems
  - name: keys
    host:
      path: /home/data/drone/key_cache

spec_step_common: &spec_step_common
  pull: if-not-exists
  volumes:
  - name: bundle
    path: /bundle
  - name: keys
    path: /ssh_keys
  commands:
    - eval $(ssh-agent -s)
    - ssh-add /ssh_keys/id_rsa
    - rm -fr Gemfile.lock gemfiles/
    - bundle install -j 5
    - bundle exec appraisal install
    - bundle exec appraisal rspec

steps:
- name: postgres
  image: abakpress/postgres-db:11
  pull: if-not-exists
  environment:
    POSTGRES_DB: docker
  detach: true

- name: redis
  image: redis:4-alpine
  pull: if-not-exists
  detach: true

- name: build on ruby2.4
  image: abakpress/ruby-app:2.4-2.0.0
  environment:
    TEST_DB_HOST: postgres
    TEST_DB_NAME: docker
    TEST_DB_USERNAME: postgres
    BUNDLE_CONFIG: /app/.bundle/config
    BUNDLE_PATH: /bundle/2.4
    TEST_REDIS_HOST: redis
    REDIS_IMAGE_TAG: 4-alpine
  <<: *spec_step_common

- name: release
  image: abakpress/gem-publication:latest
  pull: if-not-exists
  when:
    event: push
    branch: master
    status: success
  commands:
    - release-gem
